baseURL = "https://growdev-comunity.github.io/blog/"
title = "GrowDev Blog"
author = "GrowDev Comunity"
copyright = "GrowDev"
pagination.pagerSize = 15
languageCode = "en"
theme = "tailwind"

[markup]
  _merge = "deep"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  [params.header]
    logo = "https://avatars.githubusercontent.com/u/185679296?s=200&v=4"
    title = "GrowDevBlog"

  [params.footer]
    since = 2025
    poweredby = true

  [params.giscus]
    enabled = true
    repo = "GrowDev-Comunity/blog"
    repoID = "R_kgDOOYankg"
    category = "Announcements"
    categoryID = "DIC_kwDOOYanks4CpCfj"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "top"
    lang = "id"

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
